repositoryUrl: https://github.com/dynamsoft-docs/barcode-reader-docs/blob/master
repository: dynamsoft-docs/barcode-reader-docs-mobile
docFullPath: https://www.dynamsoft.com/barcode-reader/docs/mobile/
firstLevelUrl: /barcode-reader/docs/mobile
docHomePage: /barcode-reader/docs/core/introduction/

useVersionTree: true

features: /barcode-reader/docs/core/programming/features/
usecases: /barcode-reader/docs/core/programming/usecases/
introduction: /barcode-reader/docs/core/introduction/
programming: /barcode-reader/docs/core/programming/
parameters: /barcode-reader/docs/core/parameters/
license_activation: /barcode-reader/docs/core/license-activation/
release_notes: /barcode-reader/docs/core/release-notes/
performance: /barcode-reader/docs/core/performance/
faq: /barcode-reader/docs/core/faq/

faq_ios: /barcode-reader/docs/mobile/programming/objectivec-swift/faq/
faq_android: /barcode-reader/docs/mobile/programming/android/faq/

oc: /barcode-reader/docs/mobile/programming/objectivec-swift/
oc_api: /barcode-reader/docs/mobile/programming/objectivec-swift/api-reference/
oc_release_notes: /barcode-reader/docs/mobile/programming/objectivec-swift/release-notes/
oc_methods: /barcode-reader/docs/mobile/programming/objectivec-swift/api-reference/methods/
oc_class: /barcode-reader/docs/mobile/programming/objectivec-swift/api-reference/class/
oc_methods: /barcode-reader/docs/mobile/programming/objectivec-swift/api-reference/methods/

android: /barcode-reader/docs/mobile/programming/android/
android_api: /barcode-reader/docs/mobile/programming/android/api-reference/
android_release_notes: /barcode-reader/docs/mobile/programming/android/release-notes/
android_class: /barcode-reader/docs/mobile/programming/android/api-reference/class/
android_methods: /barcode-reader/docs/mobile/programming/android/api-reference/BarcodeReader/

parameters_reference: /barcode-reader/docs/core/parameters/reference/
image_parameters: /barcode-reader/docs/core/parameters/reference/image-parameter/
scenario_settings: /barcode-reader/docs/core/parameters/scenario-settings/
enumerations: /barcode-reader/docs/core/web/parameters/enum/

understanding: /barcode-reader/docs/core/web/understanding/

assets: /barcode-reader/docs/mobile/assets/
edit_icon: /barcode-reader/docs/mobile/assets/img-icon/edit-icon.png
smile_icon: /barcode-reader/docs/mobile/assets/img-icon/icon-smile.png
sad_icon: /barcode-reader/docs/mobile/assets/img-icon/icon-sad.png
dbr_icon: /barcode-reader/docs/mobile/assets/img-icon/icon-dbr.svg
dwt_icon: /barcode-reader/docs/mobile/assets/img-icon/icon-dwt.svg
dnt_icon: /barcode-reader/docs/mobile/assets/img-icon/icon-dnt.svg

camera: /camera-enhancer/docs/introduction/

baseurl: "/barcode-reader/docs/mobile"
plugins:
  - jemoji

defaults:
  - scope:
      path: ""
    values:
      category: "original-repo"
      edition: "algorithm"
  - scope:
      path: "web/programming/javascript"
    values:
      category: "js-repo"
      edition: "js"
  - scope:
      path: "mobile/programming/android"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "mobile/programming/objectivec-swift"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "server/programming/c"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/cplusplus"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/c-cplusplus"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/dotnet"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/python"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "server/programming/java"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true

url: "https://www.dynamsoft.com" # sitemap root
