repositoryUrl: https://github.com/dynamsoft-docs/barcode-reader-docs/blob/master
repositoryUrlJS: https://github.com/dynamsoft-docs/barcode-reader-docs-js/blob/main
repositoryUrlMobile: https://github.com/dynamsoft-docs/barcode-reader-docs-mobile/blob/main
repository: dynamsoft-docs/barcode-reader-docs-mobile
docFullPath: https://www.dynamsoft.com/barcode-reader-review/docs/mobile/
firstLevelUrl: /barcode-reader-review/docs/mobile
docHomePage: /barcode-reader-review/docs/core/introduction/

useVersionTree: true

features: /barcode-reader-review/docs/programming/features/
start: /barcode-reader-review/docs/mobile/
programming: /barcode-reader-review/docs/programming/
parameters: /barcode-reader-review/docs/parameters/
license_activation: /barcode-reader-review/docs/license-activation/
release_notes: /barcode-reader-review/docs/release-notes/
performance: /barcode-reader-review/docs/performance/

faq_ios: /barcode-reader-review/docs/mobile/programming/objectivec-swift/faq/
faq_android: /barcode-reader-review/docs/mobile/programming/android/faq/

oc: /barcode-reader-review/docs/mobile/programming/objectivec-swift/
oc_api: /barcode-reader-review/docs/mobile/programming/objectivec-swift/api-reference/
oc_release_notes: /barcode-reader-review/docs/mobile/programming/objectivec-swift/release-notes/
oc_methods: /barcode-reader-review/docs/mobile/programming/objectivec-swift/api-reference/methods/
oc_class: /barcode-reader-review/docs/mobile/programming/objectivec-swift/api-reference/class/
oc_methods: /barcode-reader-review/docs/mobile/programming/objectivec-swift/api-reference/methods/

android: /barcode-reader-review/docs/mobile/programming/android/
android_api: /barcode-reader-review/docs/mobile/programming/android/api-reference/
android_release_notes: /barcode-reader-review/docs/mobile/programming/android/release-notes/
android_class: /barcode-reader-review/docs/mobile/programming/android/api-reference/class/
android_methods: /barcode-reader-review/docs/mobile/programming/android/api-reference/BarcodeReader/

assets: /barcode-reader-review/docs/mobile/assets/
edit_icon: /barcode-reader-review/docs/mobile/assets/img-icon/edit-icon.png
smile_icon: /barcode-reader-review/docs/mobile/assets/img-icon/icon-smile.png
sad_icon: /barcode-reader-review/docs/mobile/assets/img-icon/icon-sad.png
dbr_icon: /barcode-reader-review/docs/mobile/assets/img-icon/icon-dbr.svg
dwt_icon: /barcode-reader-review/docs/mobile/assets/img-icon/icon-dwt.svg
dnt_icon: /barcode-reader-review/docs/mobile/assets/img-icon/icon-dnt.svg

camera: /camera-enhancer/docs/introduction/

baseurl: "/barcode-reader-review/docs/mobile"
plugins:
  - jemoji

defaults:
  - scope:
      path: ""
    values:
      category: "original-repo"
      edition: "algorithm"
  - scope:
      path: "programming/javascript"
    values:
      category: "js-repo"
      edition: "js"
  - scope:
      path: "programming/android"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming/objectivec-swift"
    values:
      category: "mobile-repo"
      edition: "mobile"
  - scope:
      path: "programming/c"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "programming/cplusplus"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "programming/c-cplusplus"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "programming/dotnet"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "programming/python"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: "programming/java"
    values:
      category: "original-repo"
      edition: "desktop"
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true

url: "https://www.dynamsoft.com" # sitemap root
