useGroupedVersion: true

version_info_list:
  - value: latest version
  - value: 9.x
    child:
      - 9.6.0
      - 9.4.0
      - 9.2.0
      - 9.0.0
  - value: 8.x
    child:
      - 8.8.0
      - 8.6.0
      - 8.4.0
      - 8.2.0
      - 8.1.2
      - 8.1.0
      - 8.0.0
  - value: 7.x
    child:
      - 7.6.0
      - 7.5.0 

version_info_list_mobile:
  - value: latest version
  - value: 9.x
    child:
      - 9.6.20
      - 9.6.11_android
      - 9.6.10
      - 9.6.0
      - 9.4.0
      - 9.2.13_ios
      - 9.2.11_android
      - 9.2.10
      - 9.0.2
      - 9.0.1
      - 9.0.0
  - value: 8.x
    child:
      - 8.9.3
      - 8.9.1
      - 8.9.0
      - 8.8.0
      - 8.6.0
      - 8.4.0
      - 8.2.1
      - 8.2.0
      - 8.1.2
      - 8.1.0
      - 8.0.0
  - value: 7.x
    child:
      - 7.6.0
      - 7.5.0