# This is a basic workflow to help you get started with Actions

name: Full-Site-Build

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DBRDocMobile ] && rm -rf DBRDocMobile 
          [ -d barcode-reader-docs-mobile ] && rm -rf barcode-reader-docs-mobile
          [ -d Docs-Template-Repo-DCV2 ] && rm -rf Docs-Template-Repo-DCV2
      - name: Build the full site (not incremental)
        run: |
          cd /home/ubuntu
          mkdir -p DBRDocMobile
          git clone --depth 1 https://github.com/dynamsoft-docs/barcode-reader-docs-mobile.git barcode-reader-docs-mobile
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-DCV2
          cp -rfp ./barcode-reader-docs-mobile/* ./DBRDocMobile/
          cp -rfp ./Docs-Template-Repo-DCV2/* ./DBRDocMobile/
          cd DBRDocMobile && bundle exec jekyll build
          #python3 /home/ubuntu/ftp.py /home/ubuntu/DBRDocMobile/_site/ ./www.dynamsoft.com/barcode-reader/docs/mobile/ prod

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_DYNAMSOFT_LOCAL_SERVER }}
          username: ${{ secrets.FTP_DYNAMSOFT_LOCAL_USER }}
          password: ${{ secrets.FTP_DYNAMSOFT_LOCAL_PASSWORD }}
          port: 21 
          local-dir: /home/ubuntu/DBRDocMobile/_site/
          server-dir: /www.dynamsoft.com/barcode-reader/docs/mobile/  
         
  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DBRDocMobile-preview ] && rm -rf DBRDocMobile-preview 
          [ -d barcode-reader-docs-mobile-preview ] && rm -rf barcode-reader-docs-mobile-preview
          [ -d Docs-Template-Repo-Preview-DCV2 ] && rm -rf Docs-Template-Repo-Preview-DCV2

      # Runs a set of commands using the runners shell
      - name: Build the Full site (not incremental)
        run: |
          cd /home/ubuntu
          mkdir -p DBRDocMobile-preview
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/barcode-reader-docs-mobile.git barcode-reader-docs-mobile-preview
          git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview-DCV2
          cp -rfp ./barcode-reader-docs-mobile-preview/* ./DBRDocMobile-preview/
          cp -rfp ./Docs-Template-Repo-Preview-DCV2/* ./DBRDocMobile-preview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DBRDocMobile-preview/_config.yml
          cd DBRDocMobile-preview && bundle exec jekyll build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DBRDocMobile-preview/_site/
          server-dir: /www.dynamsoft.com/barcode-reader/docs/mobile/         